FROM tensorflow/tensorflow:latest-gpu

RUN pip install fastapi "uvicorn[standard]"

RUN pip install torch==1.12.1+cu102 torchvision==0.13.1+cu102 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu102

RUN pip install ultralytics

RUN pip install easyocr

RUN pip install python-multipart

RUN python -c "import easyocr;easyocr.Reader(['pt','en'])"
